dist: trusty
sudo: required
language: java
jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk9
  - openjdk9
branches:
  only:
  - master
notifications:
  email:
  - eemeli.miettinen@methics.fi, matti.aarnio@methics.fi
